# Config override for deployment
version: '3'

volumes:
  wom_aworld_integration:
    external: true

services:
  web:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    volumes:
    - ./keys:/keys:ro
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=8779"
    - "traefik.frontend.rule=Host:aworld.wom.social"
    - "traefik.frontend.entryPoints=http,https"
    - "traefik.frontend.redirect.entryPoint=https"
    restart: unless-stopped

#  database:
#    volumes:
#    - wom_aworld_integration:/var/lib/mysql:rw
#    restart: unless-stopped
